apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gui-iot-binding
subjects:
- kind: ServiceAccount
  name: gui-iot-account
  namespace: iot-gui
roleRef:
  kind: ClusterRole
  name: gui-iot
  apiGroup: rbac.authorization.k8s.io
