apiVersion: v1
kind: Service
metadata:
  name: network-simluation
  namespace: iot-monitoring
spec:
  selector:
    app: network-simluation
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30069
  type: NodePort