apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ClusterRoleBinding-monitoring-kube-state-metrics.yml
- ClusterRoleBinding-monitoring-prometheus-server.yml
- ClusterRole-monitoring-kube-state-metrics.yml
- ClusterRole-monitoring-prometheus-server.yml
- ConfigMap-monitoring-prometheus-server.yml
- DaemonSet-monitoring-prometheus-node-exporter.yml
- Deployment-monitoring-kube-state-metrics.yml
- Deployment-monitoring-prometheus-pushgateway.yml
- Deployment-monitoring-prometheus-server.yml
- PersistentVolumeClaim-monitoring-prometheus-server.yml
- ServiceAccount-monitoring-kube-state-metrics.yml
- ServiceAccount-monitoring-prometheus-node-exporter.yml
- ServiceAccount-monitoring-prometheus-pushgateway.yml
- ServiceAccount-monitoring-prometheus-server.yml
- Service-monitoring-kube-state-metrics.yml
- Service-monitoring-prometheus-node-exporter.yml
- Service-monitoring-prometheus-pushgateway.yml
- Service-monitoring-prometheus-server.yml
#- Service-monitoring-nginx-metrics.yml