apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: myalpinevm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: myalpinevm
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 2Gi
        devices:
          disks:
          - name: mydisk
            disk:
              bus: virtio
      volumes:
      - name: mydisk
        containerDisk:
          image: ghcr.io/egge99/bachelor-project/alpine-iot:latest
