---
# Source: longhorn/templates/deployment-driver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    helm.sh/chart: longhorn-1.6.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.6.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-driver-deployer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: longhorn
        helm.sh/chart: longhorn-1.6.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/version: v1.6.0
        app: longhorn-driver-deployer
    spec:
      initContainers:
        - name: wait-longhorn-manager
          image: docker.io/longhornio/longhorn-manager:v1.6.0
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
      containers:
        - name: longhorn-driver-deployer
          image: docker.io/longhornio/longhorn-manager:v1.6.0
          imagePullPolicy: IfNotPresent
          command:
            - longhorn-manager
            - -d
            - deploy-driver
            - --manager-image
            - "docker.io/longhornio/longhorn-manager:v1.6.0"
            - --manager-url
            - http://longhorn-backend:9500/v1
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: CSI_ATTACHER_IMAGE
              value: "docker.io/longhornio/csi-attacher:v4.4.2"
            - name: CSI_PROVISIONER_IMAGE
              value: "docker.io/longhornio/csi-provisioner:v3.6.2"
            - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
              value: "docker.io/longhornio/csi-node-driver-registrar:v2.9.2"
            - name: CSI_RESIZER_IMAGE
              value: "docker.io/longhornio/csi-resizer:v1.9.2"
            - name: CSI_SNAPSHOTTER_IMAGE
              value: "docker.io/longhornio/csi-snapshotter:v6.3.2"
            - name: CSI_LIVENESS_PROBE_IMAGE
              value: "docker.io/longhornio/livenessprobe:v2.11.0"
      priorityClassName: "longhorn-critical"
      serviceAccountName: longhorn-service-account
      securityContext:
        runAsUser: 0
