apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h 
      receiver: 'discord-webhook'
    receivers:
    - name: 'discord-webhook'
      discord_configs:
      - webhook_url_file: '/etc/alertmanager/secrets/discord-webhook'