---
# Source: alertmanager/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-alertmanager
  labels:
    helm.sh/chart: alertmanager-1.9.0
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "v0.27.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: 'discord-webhook'
      discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1212745417134055495/XC8TbIF1SVFjQuObydyu8SYL8qsJ9d4R4wBMFLrjAKxsBpPlRPsA5HO5_RI6Uqsi3EoM'
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: 'discord-webhook'
      repeat_interval: 3h
    templates:
    - /etc/alertmanager/*.tmpl
