apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: monitoring
type: Opaque
stringData:
  url: 'https://discord.com/api/webhooks/1212745417134055495/XC8TbIF1SVFjQuObydyu8SYL8qsJ9d4R4wBMFLrjAKxsBpPlRPsA5HO5_RI6Uqsi3EoM'