---
# Source: alertmanager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-alertmanager
  labels:
    helm.sh/chart: alertmanager-1.9.0
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "v0.27.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
automountServiceAccountToken: true
