---
# Source: jaeger/templates/query-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  labels:
    helm.sh/chart: jaeger-1.0.2
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.53.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/component: query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/component: query
    spec:
      securityContext: {}
      serviceAccountName: jaeger-query
      containers:
        - name: jaeger-query
          securityContext: {}
          image: docker.io/jaegertracing/jaeger-query:1.53.0
          imagePullPolicy: IfNotPresent
          args:
          env:
            - name: SPAN_STORAGE_TYPE
              value: cassandra
            - name: CASSANDRA_SERVERS
              value: jaeger-cassandra
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_KEYSPACE
              value: jaeger_v1_test
            - name: CASSANDRA_USERNAME
              value: user
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaeger-cassandra
                  key: password
            - name: QUERY_BASE_PATH
              value: "/"
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - name: query
              containerPort: 16686
              protocol: TCP
            - name: grpc
              containerPort: 16685
              protocol: TCP
            - name: admin
              containerPort: 16687
              protocol: TCP
          resources: {}
          volumeMounts:
          livenessProbe:
            httpGet:
              path: /
              port: admin
          readinessProbe:
            httpGet:
              path: /
              port: admin
        - name: jaeger-agent-sidecar
          securityContext: {}
          image: docker.io/jaegertracing/jaeger-agent:1.53.0
          imagePullPolicy: IfNotPresent
          args:
          env:
            - name: REPORTER_GRPC_HOST_PORT
              value: jaeger-collector:14250
          ports:
            - name: admin
              containerPort: 14271
              protocol: TCP
          resources: null
          volumeMounts:
          livenessProbe:
            httpGet:
              path: /
              port: admin
          readinessProbe:
            httpGet:
              path: /
              port: admin
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
