---
# Source: jaeger/templates/cassandra-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-cassandra
  labels:
    helm.sh/chart: jaeger-1.0.2
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.53.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  password: "cGFzc3dvcmQ="
