apiVersion: v1
kind: ConfigMap
metadata:
  kind: configmap-nginx
data: 
  config: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location /[
          proxy_pass http:a
        ]
      }
    }