apiVersion: v1
kind: configMap
metadata:
  name: node-exporter-config
  namespace: monitoring
data:
  config.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['localhost 