apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-config
  namespace: monitoring
data:
  config.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['localhost:9100']
    - job_name: 'kubernetes-node-exporter'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - monitoring
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: (.+)
          replacement: ${1}:9100
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)

