apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9100'
spec:
  selector: 
    app: node-exporter
  type: NodePort  
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 30004