apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 30010
  type: NodePort
