---
# Source: nginx-ingress/templates/controller-leader-election-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-leader
  namespace: nginx
  labels:
    helm.sh/chart: nginx-ingress-1.1.3
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/managed-by: Helm
