---
# Source: nginx-ingress/templates/controller-rolebiding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-nginx-ingress
  labels:
    helm.sh/chart: nginx-ingress-1.1.3
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/managed-by: Helm
  namespace: nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-nginx-ingress
subjects:
  - kind: ServiceAccount
    name: nginx-nginx-ingress
    namespace: nginx
