---
# Source: nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-nginx-ingress-controller
  namespace: nginx
  labels:
    helm.sh/chart: nginx-ingress-1.1.3
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "3.4.3"
    app.kubernetes.io/managed-by: Helm
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - port: 80
      targetPort: 30080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 30443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx
